services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_DC: "DC1"
      CASSANDRA_RACK: "RAC1"
      CASSANDRA_SEEDS: "cassandra"
      CASSANDRA_NUM_TOKENS: 16
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
      # Allow remote JMX (test only)
      LOCAL_JMX: "no"
      # 🔓 Disable JMX auth + SSL for dev
      JVM_EXTRA_OPTS: >-
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
    ports:
      - "9042:9042"   # CQL
      - "7199:7199"   # JMX (test only)
    volumes:
      - ./data:/var/lib/cassandra
    ulimits:
      nproc: 32768
      nofile:
        soft: 1048576
        hard: 1048576
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER' 127.0.0.1 9042 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
